import { db } from "@workspace/db";
import { trailsTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const trails = [
  // Lake District
  {
    name: "Scafell Pike Summit",
    region: "Lake District",
    location: "Wasdale Head, Cumbria",
    lengthKm: 12.8,
    elevationGainM: 978,
    difficulty: "hard" as const,
    terrain: "Rocky mountain",
    scenery: "Mountain summit, tarns",
    description:
      "The classic route to England's highest peak via Wasdale Head. A challenging mountain ascent with dramatic views of the Wasdale valley and surrounding fells.",
    highlights: "Summit of England at 978m, views to Scotland on clear days, Lingmell Col",
    estimatedDurationHours: 6.5,
    popularityScore: 95,
    rating: 4.7,
    reviewCount: 3241,
    startPoint: "Wasdale Head NT car park",
    tags: JSON.stringify(["summit", "mountain", "england-highest", "challenging", "iconic"]),
  },
  {
    name: "Helvellyn via Striding Edge",
    region: "Lake District",
    location: "Patterdale, Cumbria",
    lengthKm: 14.2,
    elevationGainM: 855,
    difficulty: "hard" as const,
    terrain: "Rocky ridge, mountain",
    scenery: "Dramatic ridge, glacial cirques",
    description:
      "One of England's most famous ridge walks, crossing the spectacular knife-edge of Striding Edge before reaching the broad summit plateau of Helvellyn.",
    highlights: "Striding Edge arete, Red Tarn, summit monument, Red Pike views",
    estimatedDurationHours: 7.0,
    popularityScore: 92,
    rating: 4.8,
    reviewCount: 4102,
    startPoint: "Patterdale village car park",
    tags: JSON.stringify(["ridge", "arete", "scramble", "iconic", "exposed"]),
  },
  {
    name: "Catbells Ridge Walk",
    region: "Lake District",
    location: "Derwentwater, Keswick",
    lengthKm: 6.4,
    elevationGainM: 432,
    difficulty: "easy" as const,
    terrain: "Grassy fell, ridge",
    scenery: "Lake views, valley",
    description:
      "A Beatrix Potter-famous fell offering superb views of Derwentwater and the surrounding fells. Ideal for families and those new to Lake District walking.",
    highlights: "Derwentwater panoramas, Newlands Valley views, easy scramble sections",
    estimatedDurationHours: 3.0,
    popularityScore: 88,
    rating: 4.6,
    reviewCount: 5874,
    startPoint: "Hawse End landing, Derwentwater",
    tags: JSON.stringify(["family-friendly", "lake-views", "short", "fell"]),
  },
  {
    name: "The Langdale Pikes Circuit",
    region: "Lake District",
    location: "Great Langdale, Ambleside",
    lengthKm: 11.3,
    elevationGainM: 720,
    difficulty: "moderate" as const,
    terrain: "Rocky fell, grassy plateau",
    scenery: "Valley, crags, tarns",
    description:
      "A classic circuit taking in the iconic Langdale Pikes — Harrison Stickle, Pavey Ark and Pike of Stickle — with stunning views across the Langdale Valley.",
    highlights: "Harrison Stickle summit, Pavey Ark face, Stickle Tarn, Pike of Stickle",
    estimatedDurationHours: 5.5,
    popularityScore: 85,
    rating: 4.6,
    reviewCount: 2788,
    startPoint: "New Dungeon Ghyll Hotel car park",
    tags: JSON.stringify(["circuit", "tarn", "rocky", "views", "fell"]),
  },
  {
    name: "Wainwright's Coast to Coast – Borrowdale Section",
    region: "Lake District",
    location: "Borrowdale, Keswick",
    lengthKm: 15.7,
    elevationGainM: 650,
    difficulty: "moderate" as const,
    terrain: "Woodland, valley, fell",
    scenery: "Ancient woodland, river valley",
    description:
      "A beautiful section of Wainwright's famous 190-mile Coast to Coast walk through the lush Borrowdale valley, past waterfalls and ancient oak woodland.",
    highlights: "Lodore Falls, Derwent Water, Sour Milk Gill, Honister Pass views",
    estimatedDurationHours: 6.5,
    popularityScore: 79,
    rating: 4.5,
    reviewCount: 1423,
    startPoint: "Rosthwaite village",
    tags: JSON.stringify(["coast-to-coast", "woodland", "valley", "waterfall"]),
  },

  // Snowdonia
  {
    name: "Snowdon via Pyg Track",
    region: "Snowdonia",
    location: "Pen-y-Pass, Gwynedd",
    lengthKm: 10.5,
    elevationGainM: 723,
    difficulty: "moderate" as const,
    terrain: "Rocky mountain path",
    scenery: "Mountain, lakes, valley",
    description:
      "The Pyg Track is the most dramatic route up Wales's highest peak, offering stunning views of Glaslyn and Llydaw lakes as you ascend the rocky path to the summit.",
    highlights: "Glaslyn lake, Llydaw causeway, summit café, Wales panorama",
    estimatedDurationHours: 5.0,
    popularityScore: 97,
    rating: 4.7,
    reviewCount: 8912,
    startPoint: "Pen-y-Pass car park",
    tags: JSON.stringify(["wales-highest", "summit", "mountain", "lakes", "iconic"]),
  },
  {
    name: "Tryfan North Ridge",
    region: "Snowdonia",
    location: "Ogwen Valley, Gwynedd",
    lengthKm: 8.0,
    elevationGainM: 720,
    difficulty: "expert" as const,
    terrain: "Rocky scramble, boulders",
    scenery: "Dramatic rocky peaks, cwms",
    description:
      "Tryfan's North Ridge is one of Wales's finest scrambles — a genuine hand-and-foot route up an iconic rocky peak. Culminates with the famous Adam and Eve boulder leap.",
    highlights: "Adam and Eve boulders, exposed ridge scramble, Ogwen Valley views",
    estimatedDurationHours: 5.5,
    popularityScore: 82,
    rating: 4.8,
    reviewCount: 2341,
    startPoint: "Ogwen Cottage, A5",
    tags: JSON.stringify(["scramble", "exposed", "rocky", "expert", "iconic"]),
  },
  {
    name: "Cadair Idris – Minffordd Path",
    region: "Snowdonia",
    location: "Dolgellau, Gwynedd",
    lengthKm: 9.2,
    elevationGainM: 893,
    difficulty: "hard" as const,
    terrain: "Rocky mountain, cwm",
    scenery: "Cwm lake, cliffs, moorland",
    description:
      "The Minffordd Path is the most direct and spectacular route up Cadair Idris, climbing steeply through oak woodland before emerging at the mysterious Llyn Cau glacial lake.",
    highlights: "Llyn Cau lake, Pen y Gadair summit, Barmouth and Cardigan Bay views",
    estimatedDurationHours: 6.0,
    popularityScore: 80,
    rating: 4.6,
    reviewCount: 1876,
    startPoint: "Minffordd car park",
    tags: JSON.stringify(["cwm", "lake", "woodland", "summit", "dramatic"]),
  },
  {
    name: "Yr Wyddfa – Ranger Path",
    region: "Snowdonia",
    location: "Rhyd Ddu, Gwynedd",
    lengthKm: 13.0,
    elevationGainM: 870,
    difficulty: "moderate" as const,
    terrain: "Mountain path, grassy ridge",
    scenery: "Lakes, valley, summit",
    description:
      "The quietest of Snowdon's main routes, offering a peaceful ascent with sweeping views of the Nantlle Ridge and Moel Hebog, ideal for those seeking a less crowded experience.",
    highlights: "Llyn Cwellyn, Nantlle Ridge views, Snowdon summit, quiet route",
    estimatedDurationHours: 6.0,
    popularityScore: 71,
    rating: 4.5,
    reviewCount: 1102,
    startPoint: "Rhyd Ddu car park",
    tags: JSON.stringify(["quiet", "summit", "lake", "panoramic"]),
  },
  {
    name: "Marloes Peninsula circular",
    region: "Pembrokeshire Coast",
    location: "Marloes, Pembrokeshire",
    lengthKm: 8.2,
    elevationGainM: 220,
    difficulty: "easy" as const,
    terrain: "Coastal cliff path, farmland tracks",
    scenery: "Sea cliffs, offshore islands, sandy beaches",
    description:
      "An easy-going circuit around the Marloes Peninsula in Wales with sweeping views across St Brides Bay — classic Pembrokeshire coastline without committing to a long-distance section.",
    highlights: "Gateholm Island views, Marloes Sands, seabirds, gentle cliffs",
    estimatedDurationHours: 3.0,
    popularityScore: 82,
    rating: 4.6,
    reviewCount: 1543,
    startPoint: "Marloes village car park",
    tags: JSON.stringify(["coastal", "wales", "pembrokeshire", "family-friendly", "easy"]),
  },

  // Peak District
  {
    name: "Kinder Scout Plateau",
    region: "Peak District",
    location: "Edale, Derbyshire",
    lengthKm: 18.5,
    elevationGainM: 680,
    difficulty: "hard" as const,
    terrain: "Moorland, peat bog, gritstone",
    scenery: "Wild moorland, gritstone edges",
    description:
      "A wild circuit across the highest plateau in the Peak District — birthplace of the 1932 Mass Trespass. Crosses dramatic peat hags, gritstone edges and the famous Kinder Downfall waterfall.",
    highlights: "Kinder Downfall, Grindsbrook Clough, Jacob's Ladder, Pennine Way",
    estimatedDurationHours: 8.0,
    popularityScore: 84,
    rating: 4.5,
    reviewCount: 2543,
    startPoint: "Edale village car park",
    tags: JSON.stringify(["moorland", "wild", "waterfall", "historical", "peat"]),
  },
  {
    name: "Dovedale Stepping Stones",
    region: "Peak District",
    location: "Ashbourne, Derbyshire",
    lengthKm: 8.5,
    elevationGainM: 220,
    difficulty: "easy" as const,
    terrain: "River valley, limestone",
    scenery: "Limestone gorge, river",
    description:
      "One of the Peak District's most loved walks through the stunning limestone gorge of Dovedale, crossing the famous stepping stones and passing dramatic pinnacles and spires.",
    highlights: "Stepping stones, Thorpe Cloud, Lovers Leap, limestone pillars",
    estimatedDurationHours: 3.5,
    popularityScore: 91,
    rating: 4.6,
    reviewCount: 6123,
    startPoint: "Dovedale car park, Ilam",
    tags: JSON.stringify(["family-friendly", "limestone", "river", "stepping-stones"]),
  },
  {
    name: "Mam Tor Horseshoe",
    region: "Peak District",
    location: "Castleton, Derbyshire",
    lengthKm: 11.2,
    elevationGainM: 420,
    difficulty: "moderate" as const,
    terrain: "Grassy ridge, gritstone",
    scenery: "Ridge, valley, caverns",
    description:
      "A spectacular ridge walk along the Great Ridge connecting Mam Tor to Lose Hill, with panoramic views of the Hope Valley and Edale on both sides.",
    highlights: "Mam Tor summit, Great Ridge, Hollins Cross, Lose Hill, Hope Valley views",
    estimatedDurationHours: 4.5,
    popularityScore: 89,
    rating: 4.7,
    reviewCount: 4231,
    startPoint: "Mam Tor car park",
    tags: JSON.stringify(["ridge", "panoramic", "circuit", "accessible"]),
  },
  {
    name: "Stanage Edge Traverse",
    region: "Peak District",
    location: "Hathersage, Derbyshire",
    lengthKm: 13.0,
    elevationGainM: 340,
    difficulty: "moderate" as const,
    terrain: "Gritstone edge, moorland",
    scenery: "Gritstone escarpment, moor",
    description:
      "A stunning traverse along the longest gritstone edge in the Peak District, famous among climbers and walkers alike for its sweeping views and dramatic rock formations.",
    highlights: "Long gritstone escarpment, millstone relics, Sheffield views, heather moor",
    estimatedDurationHours: 5.5,
    popularityScore: 82,
    rating: 4.6,
    reviewCount: 3102,
    startPoint: "Dennis Knoll car park",
    tags: JSON.stringify(["gritstone", "edge", "moorland", "climbing", "views"]),
  },

  // Cairngorms
  {
    name: "Ben Macdui via Cairn Gorm",
    region: "Cairngorms",
    location: "Cairn Gorm Mountain, Aviemore",
    lengthKm: 19.5,
    elevationGainM: 1005,
    difficulty: "expert" as const,
    terrain: "High arctic plateau, boulder field",
    scenery: "Arctic plateau, corries",
    description:
      "A demanding traverse across Britain's highest arctic plateau to the second-highest summit in the UK. Navigation skills essential — one of Britain's most serious mountain walks.",
    highlights: "Ben Macdui summit (1309m), Loch Avon, the Shelter Stone, arctic flora",
    estimatedDurationHours: 9.0,
    popularityScore: 75,
    rating: 4.7,
    reviewCount: 1234,
    startPoint: "Cairn Gorm ski area car park",
    tags: JSON.stringify(["arctic-plateau", "remote", "expert", "navigation", "high-altitude"]),
  },
  {
    name: "Lairig Ghru Through-Route",
    region: "Cairngorms",
    location: "Braemar to Aviemore",
    lengthKm: 30.5,
    elevationGainM: 740,
    difficulty: "expert" as const,
    terrain: "Mountain pass, boulder field, pine forest",
    scenery: "Ancient Caledonian forest, mountain pass",
    description:
      "Scotland's classic mountain pass through the heart of the Cairngorms — a full-day or two-day traverse through ancient Caledonian pinewoods and the dramatic boulder-strewn Lairig Ghru defile.",
    highlights: "Pools of Dee, Caledonian pinewoods, Lurcher's Crag, remote wilderness",
    estimatedDurationHours: 12.0,
    popularityScore: 72,
    rating: 4.8,
    reviewCount: 876,
    startPoint: "Linn of Dee car park, Braemar",
    tags: JSON.stringify(["through-route", "remote", "forest", "classic", "expert"]),
  },
  {
    name: "Ryvoan Pass and Green Loch",
    region: "Cairngorms",
    location: "Glenmore, Aviemore",
    lengthKm: 9.5,
    elevationGainM: 280,
    difficulty: "easy" as const,
    terrain: "Forest track, mountain pass",
    scenery: "Caledonian forest, lochan",
    description:
      "A beautiful and accessible route through ancient Caledonian pinewoods to the strikingly green An Lochan Uaine (the Green Loch), a favourite of children and families.",
    highlights: "An Lochan Uaine (Green Loch), Caledonian pines, Abernethy Forest",
    estimatedDurationHours: 3.5,
    popularityScore: 80,
    rating: 4.5,
    reviewCount: 2341,
    startPoint: "Glenmore Visitor Centre",
    tags: JSON.stringify(["forest", "lochan", "family-friendly", "accessible"]),
  },

  // Yorkshire Dales
  {
    name: "Three Peaks Challenge",
    region: "Yorkshire Dales",
    location: "Horton-in-Ribblesdale, North Yorkshire",
    lengthKm: 38.6,
    elevationGainM: 1585,
    difficulty: "expert" as const,
    terrain: "Limestone moorland, bog, gravel path",
    scenery: "Limestone karst, moorland, waterfalls",
    description:
      "The famous Three Peaks Challenge taking in Pen-y-ghent, Whernside and Ingleborough in one gruelling day. A test of endurance across Yorkshire's most iconic moorland summits.",
    highlights: "Pen-y-ghent, Whernside summit, Ingleborough plateau, Hull Pot waterfall",
    estimatedDurationHours: 12.0,
    popularityScore: 90,
    rating: 4.6,
    reviewCount: 5623,
    startPoint: "Horton-in-Ribblesdale",
    tags: JSON.stringify(["challenge", "three-peaks", "endurance", "iconic", "moorland"]),
  },
  {
    name: "Malham Cove and Gordale Scar",
    region: "Yorkshire Dales",
    location: "Malham, North Yorkshire",
    lengthKm: 12.0,
    elevationGainM: 380,
    difficulty: "moderate" as const,
    terrain: "Limestone pavement, waterfall, gorge",
    scenery: "Limestone cliffs, waterfall gorge",
    description:
      "A dramatic circuit taking in two of Yorkshire's greatest geological wonders — the towering curved cliff of Malham Cove and the spectacular cascading gorge of Gordale Scar.",
    highlights: "Malham Cove limestone pavement, Gordale Scar waterfall, Janet's Foss",
    estimatedDurationHours: 5.0,
    popularityScore: 93,
    rating: 4.7,
    reviewCount: 7234,
    startPoint: "Malham village car park",
    tags: JSON.stringify(["limestone", "waterfall", "gorge", "geology", "iconic"]),
  },
  {
    name: "Ingleborough Summit",
    region: "Yorkshire Dales",
    location: "Chapel-le-Dale, North Yorkshire",
    lengthKm: 16.0,
    elevationGainM: 620,
    difficulty: "hard" as const,
    terrain: "Limestone moorland, summit plateau",
    scenery: "Karst landscape, moorland plateau",
    description:
      "A wild and exhilarating ascent to Ingleborough's broad summit plateau — one of Yorkshire's Three Peaks — across dramatic limestone karst scenery.",
    highlights: "Summit plateau with Iron Age enclosure, Ribblehead Viaduct views, potholes",
    estimatedDurationHours: 7.0,
    popularityScore: 77,
    rating: 4.5,
    reviewCount: 1876,
    startPoint: "Chapel-le-Dale car park",
    tags: JSON.stringify(["summit", "moorland", "karst", "three-peaks", "historical"]),
  },

  // Scottish Highlands
  {
    name: "Ben Nevis via Mountain Track",
    region: "Scottish Highlands",
    location: "Fort William, Highland",
    lengthKm: 17.5,
    elevationGainM: 1345,
    difficulty: "hard" as const,
    terrain: "Rocky mountain path, scree",
    scenery: "Mountain, corries, summit plateau",
    description:
      "The tourist path up Britain's highest mountain. Despite its well-trodden route, Ben Nevis remains a serious and spectacular mountain requiring proper preparation.",
    highlights: "Britain's highest point at 1345m, summit ruins, views to 100+ miles on clear days",
    estimatedDurationHours: 7.0,
    popularityScore: 98,
    rating: 4.5,
    reviewCount: 11234,
    startPoint: "Glen Nevis Visitor Centre",
    tags: JSON.stringify(["britain-highest", "summit", "mountain", "iconic", "classic"]),
  },
  {
    name: "The Aonach Eagach Ridge",
    region: "Scottish Highlands",
    location: "Glen Coe, Highland",
    lengthKm: 9.8,
    elevationGainM: 1150,
    difficulty: "expert" as const,
    terrain: "Narrow rock ridge, scramble",
    scenery: "Dramatic ridge, corries, glen",
    description:
      "Scotland's most notorious mainland ridge — a thrilling but serious scramble along a knife-edge ridge above Glen Coe. Not for the faint-hearted: exposed, technical, and utterly spectacular.",
    highlights: "Pinnacles of Meall Dearg, Am Bodach, vertiginous exposure, Glen Coe views",
    estimatedDurationHours: 8.0,
    popularityScore: 78,
    rating: 4.9,
    reviewCount: 1102,
    startPoint: "Glen Coe car park (A82)",
    tags: JSON.stringify(["scramble", "exposed", "ridge", "expert", "spectacular"]),
  },
  {
    name: "Glen Affric and Loch Beinn a'Mheadhoin",
    region: "Scottish Highlands",
    location: "Cannich, Inverness-shire",
    lengthKm: 21.0,
    elevationGainM: 450,
    difficulty: "moderate" as const,
    terrain: "Caledonian forest, lochside, moorland",
    scenery: "Ancient forest, remote loch",
    description:
      "Often described as the most beautiful glen in Scotland, Glen Affric offers a stunning long walk through ancient Caledonian pinewoods alongside sparkling lochs.",
    highlights: "Loch Affric, Loch Beinn a'Mheadhoin, Caledonian pines, red squirrels",
    estimatedDurationHours: 8.0,
    popularityScore: 83,
    rating: 4.8,
    reviewCount: 1543,
    startPoint: "Dog Falls car park, Glen Affric",
    tags: JSON.stringify(["forest", "loch", "wildlife", "remote", "beautiful"]),
  },

  // South Downs
  {
    name: "Seven Sisters Clifftop Walk",
    region: "South Downs",
    location: "Seaford to Eastbourne, East Sussex",
    lengthKm: 16.5,
    elevationGainM: 540,
    difficulty: "moderate" as const,
    terrain: "Chalk cliff tops, downland",
    scenery: "White chalk cliffs, English Channel",
    description:
      "A stunning clifftop walk along England's most dramatic chalk coastline, crossing seven undulating cliff heads above the English Channel with spectacular views to sea and land.",
    highlights: "Belle Tout lighthouse, Beachy Head, Seven Sisters chalk faces, Birling Gap",
    estimatedDurationHours: 6.5,
    popularityScore: 94,
    rating: 4.7,
    reviewCount: 8234,
    startPoint: "Seaford station / Cuckmere Haven",
    tags: JSON.stringify(["coastal", "cliffs", "chalk", "iconic", "england"]),
  },
  {
    name: "South Downs Way: Winchester to Eastbourne Highlight",
    region: "South Downs",
    location: "Ditchling Beacon, East Sussex",
    lengthKm: 13.5,
    elevationGainM: 320,
    difficulty: "easy" as const,
    terrain: "Chalk downland, grassy ridge",
    scenery: "Rolling downs, farmland, coast",
    description:
      "A beautiful section of the 100-mile South Downs Way national trail, following the broad chalk ridge with wide views across the Weald and glimpses of the sea.",
    highlights: "Ditchling Beacon, Jack and Jill windmills, Weald panoramas",
    estimatedDurationHours: 5.0,
    popularityScore: 76,
    rating: 4.4,
    reviewCount: 2341,
    startPoint: "Ditchling Beacon car park",
    tags: JSON.stringify(["national-trail", "downland", "easy", "ridge", "views"]),
  },

  // Dartmoor
  {
    name: "Haytor and Hound Tor Circuit",
    region: "Dartmoor",
    location: "Bovey Tracey, Devon",
    lengthKm: 12.8,
    elevationGainM: 380,
    difficulty: "moderate" as const,
    terrain: "Open moorland, granite tors",
    scenery: "Wild moorland, granite tors",
    description:
      "A classic Dartmoor moorland circuit visiting Haytor — the most recognisable tor on the moor — and the dramatic ruined medieval village of Hound Tor, passing ancient stone rows.",
    highlights: "Haytor granite, Hound Tor medieval village ruins, panoramic moor views",
    estimatedDurationHours: 5.0,
    popularityScore: 85,
    rating: 4.5,
    reviewCount: 3102,
    startPoint: "Haytor car park",
    tags: JSON.stringify(["moorland", "tors", "granite", "historical", "circular"]),
  },
  {
    name: "High Willhays – Dartmoor's Highest",
    region: "Dartmoor",
    location: "Okehampton, Devon",
    lengthKm: 16.0,
    elevationGainM: 490,
    difficulty: "hard" as const,
    terrain: "Remote moorland, bog, military range",
    scenery: "Wild high moorland, tors",
    description:
      "A remote and challenging walk to the highest point in southern England, crossing wild and boggy high moorland. Check military firing range times before setting out.",
    highlights: "High Willhays (621m) and Yes Tor, remote wilderness, Dartmoor ponies",
    estimatedDurationHours: 7.0,
    popularityScore: 68,
    rating: 4.4,
    reviewCount: 876,
    startPoint: "Okehampton Camp car park (when open)",
    tags: JSON.stringify(["remote", "moorland", "highest-south", "bog", "wild"]),
  },

  // Exmoor
  {
    name: "Valley of the Rocks and Watersmeet",
    region: "Exmoor",
    location: "Lynton, Devon",
    lengthKm: 14.5,
    elevationGainM: 520,
    difficulty: "moderate" as const,
    terrain: "Coastal valley, woodland, cliff",
    scenery: "Coastal cliffs, river gorge, woodland",
    description:
      "A gorgeous circuit combining the dramatic rock formations of the Valley of the Rocks with the tranquil wooded gorge of Watersmeet, Exmoor's most visited beauty spot.",
    highlights: "Valley of the Rocks, Watersmeet Victorian fishing lodge, East Lyn River",
    estimatedDurationHours: 5.5,
    popularityScore: 81,
    rating: 4.5,
    reviewCount: 2765,
    startPoint: "Lynton car park",
    tags: JSON.stringify(["coastal", "woodland", "gorge", "river", "scenic"]),
  },

  // Northumberland
  {
    name: "Hadrian's Wall: Steel Rigg to Housesteads",
    region: "Northumberland",
    location: "Once Brewed, Northumberland",
    lengthKm: 11.0,
    elevationGainM: 320,
    difficulty: "moderate" as const,
    terrain: "Rolling moorland, historic wall",
    scenery: "Whin Sill ridgeline, moorland",
    description:
      "The finest section of Hadrian's Wall walking, following the spectacular Whin Sill escarpment with the iconic Roman wall striding across the rolling Northumberland moorland.",
    highlights: "Sycamore Gap tree, Milecastle 39, Housesteads Fort, crags and whin sill",
    estimatedDurationHours: 4.5,
    popularityScore: 90,
    rating: 4.7,
    reviewCount: 5432,
    startPoint: "Steel Rigg car park",
    tags: JSON.stringify(["roman", "historical", "moorland", "wall", "iconic"]),
  },
  {
    name: "The Cheviot via Hen Hole",
    region: "Northumberland",
    location: "Wooler, Northumberland",
    lengthKm: 20.5,
    elevationGainM: 780,
    difficulty: "hard" as const,
    terrain: "Remote moorland, peat bog",
    scenery: "Wild borderland moorland",
    description:
      "A challenging remote walk to the highest point of the Cheviot Hills through the spectacular Hen Hole gorge — one of the most dramatic hidden valleys in England.",
    highlights: "The Cheviot summit, Hen Hole gorge, College Valley, remote wildness",
    estimatedDurationHours: 8.5,
    popularityScore: 65,
    rating: 4.6,
    reviewCount: 634,
    startPoint: "Hartope car park, College Valley",
    tags: JSON.stringify(["remote", "moorland", "gorge", "summit", "borderland"]),
  },

  // Cornwall
  {
    name: "Land's End to Sennen Cove Coast Path",
    region: "Cornwall",
    location: "Penzance, Cornwall",
    lengthKm: 8.5,
    elevationGainM: 290,
    difficulty: "easy" as const,
    terrain: "Coastal cliff path, granite headlands",
    scenery: "Atlantic coast, granite cliffs",
    description:
      "Walk from Britain's most westerly point along dramatic granite sea cliffs to the beautiful beach at Sennen Cove, with wild Atlantic views and ancient rock formations.",
    highlights: "Land's End, Armed Knight stack, Sennen Cove beach, Atlantic sunsets",
    estimatedDurationHours: 3.5,
    popularityScore: 87,
    rating: 4.5,
    reviewCount: 4123,
    startPoint: "Land's End visitor centre",
    tags: JSON.stringify(["coastal", "cliffs", "atlantic", "landmark", "family-friendly"]),
  },
  {
    name: "Bodmin Moor: Rough Tor and Brown Willy",
    region: "Cornwall",
    location: "Camelford, Cornwall",
    lengthKm: 12.0,
    elevationGainM: 450,
    difficulty: "moderate" as const,
    terrain: "Moorland, granite tors, bog",
    scenery: "Wild moorland, granite outcrops",
    description:
      "A wild moorland walk visiting both of Bodmin Moor's summit tors — Brown Willy, the highest point in Cornwall, and Rough Tor, a rugged granite pile with Bronze Age monuments.",
    highlights: "Brown Willy (Cornwall's highest), Rough Tor, Stannon Stone Circle, open moor",
    estimatedDurationHours: 5.0,
    popularityScore: 73,
    rating: 4.3,
    reviewCount: 1234,
    startPoint: "Rough Tor car park",
    tags: JSON.stringify(["moorland", "granite", "prehistoric", "cornwall-highest"]),
  },
];

async function seed() {
  console.log("Seeding trails...");

  // Clear existing data
  await db.delete(trailsTable);

  // Insert all trails
  const inserted = await db.insert(trailsTable).values(trails).returning({ id: trailsTable.id, name: trailsTable.name });

  console.log(`✅ Inserted ${inserted.length} trails:`);
  inserted.forEach((t) => console.log(`  - [${t.id}] ${t.name}`));
}

seed()
  .then(() => {
    console.log("Seeding complete!");
    process.exit(0);
  })
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
